# Generated by Django 3.1.6 on 2021-02-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.TextField(choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejeced')], db_index=True, default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edited_articles', to='writer.writer')),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='written_articles', to='writer.writer')),
            ],
        ),
    ]
